# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowImprimirProv.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lblpregunta = QtWidgets.QLabel(Dialog)
        self.lblpregunta.setGeometry(QtCore.QRect(70, 30, 281, 41))
        self.lblpregunta.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lblpregunta.setAlignment(QtCore.Qt.AlignCenter)
        self.lblpregunta.setObjectName("lblpregunta")
        self.cbImprimir = QtWidgets.QComboBox(Dialog)
        self.cbImprimir.setGeometry(QtCore.QRect(210, 120, 69, 22))
        self.cbImprimir.setObjectName("cbImprimir")
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setGeometry(QtCore.QRect(150, 200, 75, 23))
        self.btnOk.setObjectName("btnOk")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblpregunta.setText(_translate("Dialog", "Seleccione el orden que desee"))
        self.btnOk.setText(_translate("Dialog", "OK"))
