# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAceptar.setGeometry(QtCore.QRect(380, 430, 121, 41))
        self.btnAceptar.setObjectName("btnAceptar")
        self.lblTitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTitulo.setGeometry(QtCore.QRect(320, 50, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setStyleSheet("color: pink;\n"
"border-color: rgb(0, 0, 0);\n"
"font: 16pt \"Arial\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.085 rgba(2, 79, 0, 255), stop:0.19 rgba(50, 147, 22, 255), stop:0.275 rgba(236, 191, 49, 255), stop:0.39 rgba(243, 61, 34, 255), stop:0.555 rgba(135, 81, 60, 255), stop:0.667 rgba(121, 75, 255, 255), stop:0.825 rgba(164, 255, 244, 255), stop:0.885 rgba(104, 222, 71, 255), stop:1 rgba(93, 128, 0, 255));\n"
"")
        self.lblTitulo.setObjectName("lblTitulo")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(530, 430, 111, 41))
        self.btnSalir.setObjectName("btnSalir")
        self.lblDni = QtWidgets.QLabel(self.centralwidget)
        self.lblDni.setGeometry(QtCore.QRect(100, 70, 31, 41))
        self.lblDni.setObjectName("lblDni")
        self.txtDni = QtWidgets.QLineEdit(self.centralwidget)
        self.txtDni.setGeometry(QtCore.QRect(130, 80, 120, 20))
        self.txtDni.setObjectName("txtDni")
        self.lblValidoDni = QtWidgets.QLabel(self.centralwidget)
        self.lblValidoDni.setGeometry(QtCore.QRect(260, 82, 51, 21))
        self.lblValidoDni.setText("")
        self.lblValidoDni.setObjectName("lblValidoDni")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 672, 29))
        self.menubar.setStyleSheet("font: 16pt \"Miriam Mono CLM\";\n"
"alternate-background-color: rgb(255, 170, 255);\n"
"")
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuArchivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IMPORT-EXPORTS TEIS"))
        self.btnAceptar.setText(_translate("MainWindow", "Aceptar"))
        self.lblTitulo.setText(_translate("MainWindow", "XESTION CLIENTES"))
        self.btnSalir.setText(_translate("MainWindow", "Salir"))
        self.lblDni.setText(_translate("MainWindow", "DNI"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Ctrl+S"))
